---
abstract: 'get weighted random data'
author:
  - 'Russel Fisher <geistberg@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Random-Weighted
resources:
  homepage: https://github.com/geistberg/Data-Random-Weighted
  repository: https://github.com/geistberg/Data-Random-Weighted.git
version: 0.001
